language: java
# используем режим обычного пользователя для сборки проекта.
sudo: false

# после выполнения сборки запустить скрипт, который будет собирать статистику по JaCoCo
# Здесь используется сторонни сервис https://codecov.io/
after_success:
- bash <(curl -s https://codecov.io/bash)

jdk: openjdk-11
# Отправлять уведомление на почтуyouremail@smtp.ru(Изменить на свою) если сборка упала
notifications:
  email:
    recipients:
      geraltsx@gmail.com
    on_success: never # default: change
    on_failure: always # default: always

    env:
      global: CODECOV_TOKEN="5bca2f8d-8716-4da9-b424-3fabf71c0e23"